#!/bin/bash
set -e

SYMBOL_FILE="/usr/share/X11/xkb/symbols/id"
EVDEV_XML="/usr/share/X11/xkb/rules/evdev.xml"

# 1. Bersihkan entri lama
sed -i '/\/\/ Layout start/,/\/\/end/d' "$SYMBOL_FILE"

# 2. Tambahkan simbol Kaganga Sundanese
cat <<EOF >> "$SYMBOL_FILE"

// Layout start
partial alphanumeric_keys
xkb_symbols "kaganga-sundanese" {
    name[Group1]= "Kaganga Sundanese";
    key.type = "FOUR_LEVEL";
    key <TLDE> { [ grave,          asciitilde                               ] };
    key <AE01> { [ U1BB1,          exclam                                   ] };
    key <AE02> { [ U1BB2,          at                                       ] };
    key <AE03> { [ U1BB3,          numbersign                               ] };
    key <AE04> { [ U1BB4,          dollar                                   ] };
    key <AE05> { [ U1BB5,          percent                                  ] };
    key <AE06> { [ U1BB6,          asciicircum                              ] };
    key <AE07> { [ U1BB7,          ampersand                                ] };
    key <AE08> { [ U1BB8,          asterisk                                 ] };
    key <AE09> { [ U1BB9,          parenleft                                ] };
    key <AE10> { [ U1BB0,          parenright                               ] };
    key <AE11> { [ minus,          underscore                               ] };
    key <AE12> { [ equal,          plus                                     ] };
    key <AD01> { [ U1B8B,          VoidSymbol,  VoidSymbol,  VoidSymbol     ] };
    key <AD02> { [ U1B9D,          U1BAD,       VoidSymbol,  VoidSymbol     ] };
    key <AD03> { [ U1B88,          U1BA8,       U1B86,       U1BA6          ] };
    key <AD04> { [ U1B9B,          U1BA2,       U1B81,       U1BBB          ] };
    key <AD05> { [ U1B92,          VoidSymbol,  VoidSymbol,  VoidSymbol     ] };
    key <AD06> { [ U1B9A,          U1B91,       U1BA1,       VoidSymbol     ] };
    key <AD07> { [ U1B85,          U1BA5,       VoidSymbol,  VoidSymbol     ] };
    key <AD08> { [ U1B84,          U1BA4,       U1B89,       U1BA9          ] };
    key <AD09> { [ U1B87,          U1BA7,       VoidSymbol,  VoidSymbol     ] };
    key <AD10> { [ U1B95,          VoidSymbol,  VoidSymbol,  VoidSymbol     ] };
    key <AD11> { [ bracketleft,    braceleft,   VoidSymbol,  VoidSymbol     ] };
    key <AD12> { [ bracketright,   braceright,  VoidSymbol,  VoidSymbol     ] };
    key <AC01> { [ U1B83,          VoidSymbol,  VoidSymbol,  VoidSymbol     ] };
    key <AC02> { [ U1B9E,          U1BAF,       VoidSymbol,  VoidSymbol     ] };
    key <AC03> { [ U1B93,          VoidSymbol,  VoidSymbol,  VoidSymbol     ] };
    key <AC04> { [ U1B96,          VoidSymbol,  VoidSymbol,  VoidSymbol     ] };
    key <AC05> { [ U1B8C,          U1B80,       VoidSymbol,  VoidSymbol     ] };
    key <AC06> { [ U1BA0,          U1B82,       U1BAE,       VoidSymbol     ] };
    key <AC07> { [ U1B8F,          VoidSymbol,  VoidSymbol,  VoidSymbol     ] };
    key <AC08> { [ U1B8A,          U1BBE,       VoidSymbol,  VoidSymbol     ] };
    key <AC09> { [ U1B9C,          U1BA3,       U1BBC,       VoidSymbol     ] };
    key <AC10> { [ semicolon,      colon,       VoidSymbol,  VoidSymbol     ] };
    key <AC11> { [ apostrophe,     quotedbl,    VoidSymbol,  VoidSymbol     ] };
    key <AB01> { [ U1B90,          VoidSymbol,  VoidSymbol,  VoidSymbol     ] };
    key <AB02> { [ U1B9F,          VoidSymbol,  VoidSymbol,  VoidSymbol     ] };
    key <AB03> { [ U1B8E,          VoidSymbol,  VoidSymbol,  VoidSymbol     ] };
    key <AB04> { [ U1B97,          VoidSymbol,  VoidSymbol,  VoidSymbol     ] };
    key <AB05> { [ U1B98,          U1BBD,       VoidSymbol,  VoidSymbol     ] };
    key <AB06> { [ U1B94,          U1B8D,       VoidSymbol,  VoidSymbol     ] };
    key <AB07> { [ U1B99,          U1BAC,       U1BBF,       VoidSymbol     ] };
    key <AB08> { [ comma,          less,        VoidSymbol,  VoidSymbol     ] };
    key <AB09> { [ period,         greater,     VoidSymbol,  VoidSymbol     ] };
    key <AB10> { [ slash,          question,    VoidSymbol,  VoidSymbol     ] };
    key <BKSL> { [ backslash,      U1BAA,       U1BAB,       U1BBA          ] };
    include "level3(ralt_switch)"
};
//end
EOF

# 3. Daftarkan varian ke evdev.xml
if ! grep -q "kaganga-sundanese" "$EVDEV_XML"; then
    VAR_ENTRY="<variant><configItem><name>kaganga-sundanese</name><description>Kaganga Sundanese</description></configItem></variant>"
    sed -i "\|<name>javanese</name>|,\|</variant>| { \|</variant>| s|</variant>|</variant>\n        $VAR_ENTRY| }" "$EVDEV_XML"
fi

# 4. Bersihkan Cache
fc-cache -fv > /dev/null
rm -rf /var/lib/xkb/*.xkm

# 5. Pasang ke GNOME Input Sources (User Active)
if [ -n "$SUDO_USER" ]; then
    USER_ID=$(id -u "$SUDO_USER")
    export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$USER_ID/bus"
    if [ -S "/run/user/$USER_ID/bus" ]; then
        CURRENT_SOURCES=$(sudo -u "$SUDO_USER" gsettings get org.gnome.desktop.input-sources sources)
        if [[ "$CURRENT_SOURCES" != *"'id+kaganga-sundanese'"* ]]; then
            NEW_SOURCES="${CURRENT_SOURCES%]*}, ('xkb', 'id+kaganga-sundanese')]"
            sudo -u "$SUDO_USER" gsettings set org.gnome.desktop.input-sources sources "$NEW_SOURCES"
        fi
    fi
fi

exit 0
